### ISSUE TITLE
Is this meant to be an Antlr4 importer?

### ISSUE THREAD

**Issue by martaver** [langium/antlr4-grammar#1]
As in, will Langium be able to serve as a bridge between antlr4 grammars and LSP?
Or is this repo simply to re-implement all antlr4 grammars in Langium's own syntax?

**Comment by Lotes** [comment]
My original idea was to create a transpiler from an ANTLR grammar to a Langium grammar. Because I like the fact that there so many ANTLR4 grammars. Would it not be cool to have a Langium start grammar derived from an ANTLR4 grammar?

But on the short run it could be an in-browser language server for projects like [Antlr lab](http://lab.antlr.org/).

**Comment by martaver** [comment]
I'm interested in langium because it can generate a language server that's browser compatible via wasm. Being able to extend an existing ecosystem of grammars would make langium quite a strong contender.
